JESI-3014
jesims/bindle pull request #1
Opened 2020-01-09 07:32 UTC by AndreTheHunter

[JESI-3014](https://jesims.atlassian.net/browse/JESI-3014)

2020-01-16 00:59 UTC, BadAlgorithm requested changes

2020-01-16 00:59 UTC, BadAlgorithm commented on README.md
> +Public build scripts.
Should we allude to the fact we have a private build scripts?

perhaps something like
```suggestion
Build tool scripts.
```

2020-01-16 01:00 UTC, BadAlgorithm submitted a review, later dismissed

2020-01-17 00:17 UTC, BadAlgorithm submitted a review, later dismissed

2020-01-20 01:32 UTC, BadAlgorithm submitted a review, later dismissed

2020-01-20 01:35 UTC, axrs requested changes
Smol

2020-01-20 01:35 UTC, axrs commented on .circleci/config.yml
> +          DEBUG: 1
`JVM_OPTS` and `DEBUG` shouldn't be required.

2020-01-20 01:35 UTC, axrs commented on README.md
> +source bindle/project.sh
Add the `|| exit 1`?

2020-01-20 02:03 UTC, axrs submitted a review, later dismissed

2020-01-20 04:30 UTC, BadAlgorithm submitted a review, later dismissed

2020-01-29 00:06 UTC, BadAlgorithm requested changes

2020-01-29 00:06 UTC, BadAlgorithm commented on project.sh
> +	file-exists 'package.json'
Indentation here is inconsistent

2020-01-29 00:56 UTC, axrs commented on project.sh
> +	file-exists 'pom.xml'
check pom.xml exists and project.clj does not?

2020-01-29 00:59 UTC, axrs commented on project.sh
> +	if is-java;then
won't this do a lein, generate pom, then run the java as-well?

2020-01-29 01:00 UTC, axrs reviewed
💬

2020-01-29 01:00 UTC, AndreTheHunter commented on project.sh
> +		lein-dev pom
FIXME combine with `lein do`

2020-01-29 01:01 UTC, AndreTheHunter commented on project.sh
> +	if is-java;then
Yup. `lein ancient` doesn't pick up all the java maven dependencies, so it's good to use maven to check also
Do lein then java, like `-deps` does

2020-01-29 01:02 UTC, AndreTheHunter commented on project.sh
> +	file-exists 'pom.xml'
Nah, if a project needs that it can go `is-lein && ! is-java`

2020-01-29 01:42 UTC, axrs submitted a review, later dismissed

2020-01-29 02:15 UTC, BadAlgorithm submitted a review, later dismissed

2020-02-04 02:29 UTC, BadAlgorithm approved these changes

2020-02-04 02:37 UTC, axrs approved these changes

2020-02-04 05:11 UTC, merged